spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/socialzr_dev
    username: socialzr_dev_user
    password: szymek
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true
  main:
    allow-circular-references: true
  #Uncomment lines below to generate script with schema
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: src/main/scripts/socialzr_db_create.sql
server:
  servlet:
    context-path: /api/v1
