create table comment (id bigint not null auto_increment, text varchar(255), author_id bigint, post_id bigint, primary key (id)) engine=InnoDB;
create table contact_information (id bigint not null auto_increment, address varchar(255), city varchar(255), country varchar(255), state varchar(255), email varchar(255), phone_number varchar(255), primary key (id)) engine=InnoDB;
create table post (id bigint not null auto_increment, text longtext, post_author_id bigint, primary key (id)) engine=InnoDB;
create table social_group (id bigint not null auto_increment, access_level varchar(255), description varchar(255), name varchar(255), creator_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), contact_information_id bigint, primary key (id)) engine=InnoDB;
create table user_social_group (social_group_id bigint not null, user_id bigint not null) engine=InnoDB;create table comment (id bigint not null auto_increment, text varchar(255), author_id bigint, post_id bigint, primary key (id)) engine=InnoDB;
create table contact_information (id bigint not null auto_increment, address varchar(255), city varchar(255), country varchar(255), state varchar(255), email varchar(255), phone_number varchar(255), primary key (id)) engine=InnoDB;
create table post (id bigint not null auto_increment, text longtext, post_author_id bigint, primary key (id)) engine=InnoDB;
create table social_group (id bigint not null auto_increment, access_level varchar(255), description varchar(255), name varchar(255), creator_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), contact_information_id bigint, primary key (id)) engine=InnoDB;
create table user_social_group (social_group_id bigint not null, user_id bigint not null) engine=InnoDB;
alter table comment add constraint FKh1gtv412u19wcbx22177xbkjp foreign key (author_id) references user (id);
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id);
alter table post add constraint FKb148lg77kvu587eo11pik17ot foreign key (post_author_id) references user (id);
alter table social_group add constraint FKe5ffhh7emtqqret2ih8a11ac1 foreign key (creator_id) references user (id);
alter table user add constraint FKd6n162q6610mf20yxqyk8i770 foreign key (contact_information_id) references contact_information (id);
alter table user_social_group add constraint FKctsr7e96wagidmivc1ep5ilme foreign key (user_id) references user (id);
alter table user_social_group add constraint FK1lbb9idihcfnv6ybvkeiwy26o foreign key (social_group_id) references social_group (id);
create table comment (id bigint not null auto_increment, text varchar(255), author_id bigint, post_id bigint, primary key (id)) engine=InnoDB;
create table contact_information (id bigint not null auto_increment, address varchar(255), city varchar(255), country varchar(255), state varchar(255), email varchar(255), phone_number varchar(255), primary key (id)) engine=InnoDB;
create table post (id bigint not null auto_increment, text longtext, post_author_id bigint, primary key (id)) engine=InnoDB;
create table social_group (id bigint not null auto_increment, access_level varchar(255), description varchar(255), name varchar(255), creator_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), contact_information_id bigint, primary key (id)) engine=InnoDB;
create table user_social_group (social_group_id bigint not null, user_id bigint not null) engine=InnoDB;
alter table comment add constraint FKh1gtv412u19wcbx22177xbkjp foreign key (author_id) references user (id);
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id);
alter table post add constraint FKb148lg77kvu587eo11pik17ot foreign key (post_author_id) references user (id);
alter table social_group add constraint FKe5ffhh7emtqqret2ih8a11ac1 foreign key (creator_id) references user (id);
alter table user add constraint FKd6n162q6610mf20yxqyk8i770 foreign key (contact_information_id) references contact_information (id);
alter table user_social_group add constraint FKctsr7e96wagidmivc1ep5ilme foreign key (user_id) references user (id);
alter table user_social_group add constraint FK1lbb9idihcfnv6ybvkeiwy26o foreign key (social_group_id) references social_group (id);
create table comment (id bigint not null auto_increment, text varchar(255), author_id bigint, post_id bigint, primary key (id)) engine=InnoDB;
create table contact_information (id bigint not null auto_increment, address varchar(255), city varchar(255), country varchar(255), state varchar(255), email varchar(255), phone_number varchar(255), primary key (id)) engine=InnoDB;
create table post (id bigint not null auto_increment, text longtext, post_author_id bigint, primary key (id)) engine=InnoDB;
create table social_group (id bigint not null auto_increment, access_level varchar(255), description varchar(255), name varchar(255), creator_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), contact_information_id bigint, primary key (id)) engine=InnoDB;
create table user_social_group (social_group_id bigint not null, user_id bigint not null) engine=InnoDB;
alter table comment add constraint FKh1gtv412u19wcbx22177xbkjp foreign key (author_id) references user (id);
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id);
alter table post add constraint FKb148lg77kvu587eo11pik17ot foreign key (post_author_id) references user (id);
alter table social_group add constraint FKe5ffhh7emtqqret2ih8a11ac1 foreign key (creator_id) references user (id);
alter table user add constraint FKd6n162q6610mf20yxqyk8i770 foreign key (contact_information_id) references contact_information (id);
alter table user_social_group add constraint FKctsr7e96wagidmivc1ep5ilme foreign key (user_id) references user (id);
alter table user_social_group add constraint FK1lbb9idihcfnv6ybvkeiwy26o foreign key (social_group_id) references social_group (id);
